apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.streamlit.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.streamlit.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.streamlit.name }}
    spec:
      containers:
        - name: streamlit-container
          image: "{{ .Values.streamlit.image.repository }}:{{ .Values.streamlit.image.tag }}"
          imagePullPolicy: {{ .Values.streamlit.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: results-storage
              mountPath: /data
      volumes:
        - name: results-storage
          persistentVolumeClaim:
            claimName: results-pvc
