apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.streamlit.serviceName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.streamlit.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
